source 'https://rubygems.org'
gem 'dotenv',                       '~> 2.8', '>= 2.8.1'
gem 'websocket-client-simple',      '~> 0.6.0'
gem 'puma',                         '~> 6.0'
gem 'httparty',                     '~> 0.20.0'
